id: A65563122
title: Verses in Praise of the Protector Akṣobhya
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:04:10.546924
  last_modified_at: 2022-02-28 23:04:10.546948
