id: A65563122
title: 'Prayer to Tārā: A Sevenfold Supplication for Protection'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:04:10.544887
  last_modified_at: 2022-02-28 23:04:10.544913
