id: A65563122
title: 'Praise of the Buddha: With Skilful Means & Compassion...'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:04:10.541430
  last_modified_at: 2022-02-28 23:04:10.541437
